db:
  refreshIntervalSec: 86400
  preCropImages: false
server:
  port: 7070
  hostName: localhost
  contextPath: /
  prometheus: true
website:
  imprint: Test Name\nTest Address1\nTestAddress2\nTest E-mail
reuseHtml: true