app.title=Trooper Card Generator
form.army.label=Army Code or Option IDs:
form.army.placeholder=Enter Army Code OR comma-separated Option IDs...
form.style.label=Select Card Style:
style.a4_image=Color and image - one per Page
style.c6onA4_image=Color and image - 6 on one page
style.a4_overview=Overview List
style.card_bw=Black and white - playing card (legacy and no options)

adv.summary=Advanced Options
adv.useCm=Use cm instead of inch
adv.useLetter=Use Letter format instead of A4
adv.showSectorial=Show Sectorial Icon in the background
adv.showUnitIcon=Show Unit Icon
adv.showUnitImages=Show Unit Images
adv.reduceColor=Reduced color (better for black and white printers)
adv.distinctUnits=Remove duplicate units (removes also combat group number)
adv.showAlwaysOption=Always, if space allows, append unique skills/weapons/equipment of the option to the unit's name.
adv.showOptionFeature=If there are multiple options of the same unit and if space allows, append unique skills/weapons/equipment of the option to the unit's name.
adv.showCombatGroup=Show Combat Group number
adv.showEquipment=Show Equipment Weapons (e.g. Medkit ...)
adv.showSkillWeapon=Show Skill Weapon (e.g. Forward Observer ...)
adv.showHacking=Show Card with Hacking Programs
adv.showWeaponSkillCol=Show Weapon Skill column
adv.showBurst=Show Burst column
adv.showSavingRoll=Show Saving Roll column
adv.showAmmo=Show Ammo column
adv.showPs=Show PS column
adv.showSaveAttribute=Show Saving Attribute column
adv.showNumberSaveRolls=Show Number Saving Rolls column
adv.showWeaponTraits=Show Weapon Traits column
adv.applyingSkillWeapon=Apply Weapon Skill Modifier (Burst, SR ...) to weapons and remove from skill list

btn.generate=Generate and View Cards
link.downloadAll=Download all Units as CSV
link.oldChanges=(old/changes)
link.avaChecker=Joined Army List AVA Checker
link.help=Help
footer.contact=Contact
footer.imprint=Imprint
footer.source=Source Code
footer.thanks=Special thanks to the following contributors for helping with the images:
footer.and=\ and