package de.twonirwana.infinity.armylist;

import com.google.common.annotations.VisibleForTesting;
import de.twonirwana.infinity.ArmyList;
import de.twonirwana.infinity.Database;
import de.twonirwana.infinity.Sectorial;
import de.twonirwana.infinity.db.DataLoader;
import de.twonirwana.infinity.model.specops.Attribute;
import de.twonirwana.infinity.model.specops.Item;
import de.twonirwana.infinity.unit.api.ModifierOption;
import de.twonirwana.infinity.unit.api.UnitOption;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

import java.net.URLDecoder;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * # Army Codes
 * These are the shorthand codes generated by Army builder representing an army. They are base64 encoded strings.
 * <p>
 * ## Numbers
 * Integers are stored using a form of variable length encoding. If the value is under 128, then it is stored in a byte normally.
 * For larger numbers, two bytes are used and the first bit of the first byte is set high to flag this.
 * Should a larger number still be required, then presumably it would go up to 6 bytes, but no number in the game gets remotely that high.
 * <p>
 * ## Strings
 * Strings are encoded in the form `length, text`. and are not null terminated. 0 is a valid value for string length (in which case the text part will be absent).
 * <p>
 * ## Code Structure.
 * The code can be broken down into two parts - the header and the combat groups.
 * <p>
 * ### Header
 * The header is laid out as follows:
 * ````
 * ID of sectorial (int)
 * Name of sectorial (string)
 * Name of the army (string) - defaults to ' '
 * Point _limit_ used (int)
 * Number of combat groups (int)
 * ````
 * <p>
 * ### Combat Groups
 * Each combat group is as follows:
 * ````
 * 10
 * combat group number (int)
 * number of members of the group (int)
 * combat group member (see below) x number of members
 * ````
 * <p>
 * #### Combat Group Members
 * Each of these corresponds to a line in the army list in army builder.
 * ```
 * 00 (an empty byte)
 * Unit ID (int)
 * Group choice (int)
 * Option choice (int)
 * 00 (an empty byte)
 * ```
 */

@Slf4j
public class ArmyCodeLoader {

    private static final ObjectMapper objectMapper = new ObjectMapper();

    private static int readInt(ByteBuffer data) {
        byte firstByte = data.get();

        // If the highest bit is 0, it's a standard positive byte (under 128)
        if (firstByte >= 0) {
            return firstByte;
        }

        // Otherwise, the first bit was 1.
        // We clear that flag bit (firstByte & 0x7F), shift it up 8 spots,
        // and combine it with the next byte.
        byte secondByte = data.get();
        return ((firstByte & 0x7F) << 8) | (secondByte & 0xFF);
    }

    private static Integer tryReadInteger(ByteBuffer data) {
        if (!data.hasRemaining()) {
            return null;
        }
        byte firstByte = data.get();

        // If the highest bit is 0, it's a standard positive byte (under 128)
        if (firstByte >= 0) {
            return (int) firstByte;
        }

        // Otherwise, the first bit was 1.
        // We clear that flag bit (firstByte & 0x7F), shift it up 8 spots,
        // and combine it with the next byte.
        if (!data.hasRemaining()) {
            return null;
        }
        byte secondByte = data.get();
        return ((firstByte & 0x7F) << 8) | (secondByte & 0xFF);
    }

    public static ArmyList fromArmyCode(final String armyCode, DataLoader dataLoader) throws IllegalArgumentException {
        ArmyCodeData armyCodeData;
        try {
            armyCodeData = mapArmyCode(armyCode);
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }
        Sectorial sectorial = dataLoader.getSectorialIdMap().get(armyCodeData.sectorialId);
        List<UnitOption> unitOptionList = dataLoader.getAllUnitsForSectorial(sectorial);

        Sectorial sectorialApiId = dataLoader.getAllSectorialIds().stream()
                .filter(s -> s.getId() == armyCodeData.sectorialId)
                .findFirst().orElseThrow(() -> new IllegalArgumentException("Could not find sectorial with id %d for %s".formatted(armyCodeData.sectorialId, armyCode)));
        Map<Integer, List<UnitOption>> combatGroups = armyCodeData.combatGroups.entrySet().stream()
                .collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().stream()
                        .flatMap(m -> findUnitOptions(m, unitOptionList).stream())
                        .toList()));
        return new ArmyList(sectorialApiId, armyCodeData.sectorialName, armyCodeData.armyName, armyCodeData.maxPoints, combatGroups);
    }

    @VisibleForTesting
    public static ArmyCodeData mapArmyCode(final String armyCode) {
        byte[] decoded = decodeArmyCode(armyCode);
        if (decoded == null) {
            throw new IllegalArgumentException("armyCode cannot be null");
        }

        ByteBuffer data = ByteBuffer.wrap(decoded);

        int sectorialId = readInt(data);
        int factionStringLength = readInt(data);

        String fractionName = readString(data, factionStringLength);

        // Get the army name, if set. The default army name is ' '.
        int armyNameLength = readInt(data);
        String armyName = null;
        if (armyNameLength > 0) {
            armyName = readString(data, armyNameLength);
        }

        int maxPoints = readInt(data);

        int combatGroupCount = readInt(data);
        Map<Integer, List<CombatGroupMember>> combatGroups = new HashMap<>();
        //readNumbersTillEnd(data);
        for (int i = 1; i <= combatGroupCount; i++) {
            List<CombatGroupMember> match = getCombatGroupFromCodeV0(data)
                    .or(() -> getCombatGroupFromCodeV00(data))
                    .or(() -> getCombatGroupFromCodeV0L0E(data))
                    .or(() -> getCombatGroupFromCodeV1_01SpecOps(data)) //need to be before getCombatGroupFromCodeV1_00
                    .or(() -> getCombatGroupFromCodeV1_00(data))
                    .or(() -> getCombatGroupFromCodeV1_000(data))
                    .or(() -> getCombatGroupFromCodeV1_0subVersionCounter(data))
                    .or(() -> getCombatGroupFromCodeV1_00subVersionCounter(data))
                    .orElse(null);
            if (match != null) {
                combatGroups.put(i, match);
            }

        }

        return new ArmyCodeData(sectorialId, fractionName, armyName, maxPoints, combatGroups);
    }

    @VisibleForTesting
    static boolean canMapModifier(String in) {
        try {
            objectMapper.readValue(in, new TypeReference<List<Attribute>>() {
            });
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    private static Item mapToItem(String in) {
        try {
            List<Attribute> attributes = objectMapper.readValue(in, new TypeReference<>() {
            });
            Item item = new Item();
            item.setAttrs(attributes);
            return item;
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }
    }

    public static List<Database.ValidationError> missingUnitsInArmyCode(final String armyCode, DataLoader dataLoader) throws IllegalArgumentException {
        ArmyCodeData armyCodeData;
        try {
            armyCodeData = mapArmyCode(armyCode);
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }

        Sectorial sectorial = dataLoader.getSectorialIdMap().get(armyCodeData.sectorialId);
        List<UnitOption> unitsForSectorial = dataLoader.getAllUnitsForSectorial(sectorial);
        List<UnitOption> allUnits = dataLoader.getAllUnits();

        return armyCodeData.combatGroups.values().stream()
                .flatMap(Collection::stream)
                .flatMap(c -> {
                    List<UnitOption> foundUnitOptions = findUnitOptions(c, unitsForSectorial);
                    String unitName = allUnits.stream()
                            .filter(u -> u.getUnitId() == c.unitId())
                            .map(UnitOption::getUnitName)
                            .findFirst().orElse("");
                    if (foundUnitOptions.isEmpty()) {
                        return Stream.of(new Database.ValidationError(c.unitId(), c.groupId(), c.optionId(), unitName, "Unit option not found in sectorial"));
                    }

                    if (foundUnitOptions.size() > 1) {
                        return Stream.of(new Database.ValidationError(c.unitId(), c.groupId(), c.optionId(), unitName, "Non unique id"));

                    }
                    for (String m : c.modifier()) {
                        if (!canMapModifier(m)) {
                            return Stream.of(new Database.ValidationError(c.unitId(), c.groupId(), c.optionId(), unitName, "Invalid modifier: " + m));
                        }
                        //todo check if modifier match with options
                    }
                    return Stream.empty();
                })
                .toList();
    }

    private static List<UnitOption> findUnitOptions(CombatGroupMember combatGroupMember, List<UnitOption> unitOptionList) {
        List<UnitOption> units = unitOptionList.stream()
                .filter(uo -> uo.getUnitId() == combatGroupMember.unitId()
                        && uo.getGroupId() == combatGroupMember.groupId()
                        && uo.getOptionId() == combatGroupMember.optionId())
                .toList();
        if (combatGroupMember.modifier().isEmpty()) {
            return units;
        }
        return units.stream()
                .map(u -> {
                    Set<String> selectedOptionsKeys = combatGroupMember.modifier().stream()
                            .map(ArmyCodeLoader::mapToItem)
                            .map(Item::toKey)
                            .collect(Collectors.toSet());
                    List<ModifierOption> selected = u.getSpecOpsOptions().stream()
                            .filter(m -> selectedOptionsKeys.contains(m.getKey()))
                            .toList();

                    return u.copyWithSelectedOptions(selected);
                })
                .toList();
    }

    //0 between groupMembers
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV0(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int combatGroupSize = readInt(data);
        List<CombatGroupMember> group = new ArrayList<>();

        for (int i = 0; i < combatGroupSize; i++) {
            int fillerCounter = readInt(data);
            if (fillerCounter != i + 1) {
                data.position(resetPosition);
                return Optional.empty();
            }

            CombatGroupMember combatGroupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);
            // System.out.println("UnitId: " + unitId + "-" + groupId + "-" + optionId);

            int fillerZero = readInt(data);
            if (fillerZero != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }

            combatGroupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(combatGroupMember);
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }

        return Optional.of(group);
    }

    //leading counter, 00 between groupMembers
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV00(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int combatGroupSize = readInt(data);
        List<CombatGroupMember> group = new ArrayList<>();

        for (int i = 0; i < combatGroupSize; i++) {
            int fillerCounter = readInt(data);
            if (fillerCounter != i + 1) {
                data.position(resetPosition);
                return Optional.empty();
            }

            CombatGroupMember combatGroupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);
            // System.out.println("UnitId: " + unitId + "-" + groupId + "-" + optionId);

            int fillerZero = readInt(data);
            if (fillerZero != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }
            int fillerZero2 = readInt(data);
            if (fillerZero2 != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }

            combatGroupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(combatGroupMember);
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }

        return Optional.of(group);
    }

    //leading 0, 0 between groupMembers
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV0L0E(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int combatGroupSize = readInt(data);
        List<CombatGroupMember> group = new ArrayList<>();

        for (int i = 0; i < combatGroupSize; i++) {
            int fillerCounter = readInt(data);
            if (fillerCounter != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }

            CombatGroupMember combatGroupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);
            // System.out.println("UnitId: " + unitId + "-" + groupId + "-" + optionId);

            int fillerZero = readInt(data);
            if (fillerZero != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }

            combatGroupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(combatGroupMember);
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }

        return Optional.of(group);
    }

    //no counter, 00 between groupMembers, no specOps
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV1_00(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 1) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int reinforcement = readInt(data);
        int combatGroupSize = readInt(data);
        int subVersion = readInt(data);

        List<CombatGroupMember> group = new ArrayList<>();

        for (int i = 0; i < combatGroupSize; i++) {

            CombatGroupMember groupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);

            groupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(groupMember);

            //not behind the last in the group
            if (i < combatGroupSize - 1) {
                int memberFillerZero1 = readInt(data);
                if (memberFillerZero1 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                Integer someNumber = tryReadInteger(data);
                if (someNumber == null) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
            }
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZeroOrOne = readInt(data);
        if (!Set.of(0, 1).contains(inBetweenGroupZeroOrOne)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        return Optional.of(group);
    }

    //no counter, 000 between groupMembers, no specOps
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV1_000(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 1) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int reinforcement = readInt(data);
        int combatGroupSize = readInt(data);
        int subVersion = readInt(data);

        List<CombatGroupMember> group = new ArrayList<>();

        for (int i = 0; i < combatGroupSize; i++) {

            CombatGroupMember groupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);

            groupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(groupMember);

            //not behind the last in the group
            if (i < combatGroupSize - 1) {
                int memberFillerZero1 = readInt(data);
                if (memberFillerZero1 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                int memberFillerZero2 = readInt(data);
                if (memberFillerZero2 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                int memberFillerZero3 = readInt(data);
                if (memberFillerZero3 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
            }
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZero = readInt(data);
        if (inBetweenGroupZero != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZero2 = readInt(data);
        if (inBetweenGroupZero2 != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        return Optional.of(group);
    }

    //no 0 + subVersionCounter between groupMembers, no specOps
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV1_0subVersionCounter(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 1) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int reinforcement = readInt(data);
        int combatGroupSize = readInt(data);
        int subVersion = readInt(data);

        List<CombatGroupMember> group = new ArrayList<>();
        int counter = subVersion;
        for (int i = 0; i < combatGroupSize; i++) {

            CombatGroupMember groupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);

            groupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(groupMember);
            counter++;
            //not behind the last in the group
            if (i < combatGroupSize - 1) {
                int memberFillerZero1 = readInt(data);
                if (memberFillerZero1 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                int memberFillerCounter = readInt(data);
                if (memberFillerCounter != counter) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
            }
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZero = readInt(data);
        if (inBetweenGroupZero != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        return Optional.of(group);
    }

    //no 00 + subVersionCounter between groupMembers, no specOps
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV1_00subVersionCounter(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 1) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int reinforcement = readInt(data);
        int combatGroupSize = readInt(data);
        int subVersion = readInt(data);

        List<CombatGroupMember> group = new ArrayList<>();
        int counter = subVersion;
        for (int i = 0; i < combatGroupSize; i++) {

            CombatGroupMember groupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);

            groupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    List.of()
            );
            group.add(groupMember);
            counter++;
            //not behind the last in the group
            if (i < combatGroupSize - 1) {
                int memberFillerZero1 = readInt(data);
                if (memberFillerZero1 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                int memberFillerZero2 = readInt(data);
                if (memberFillerZero2 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
                int memberFillerCounter = readInt(data);
                if (memberFillerCounter != counter) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
            }
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZero = readInt(data);
        if (inBetweenGroupZero != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int inBetweenGroupZero2 = readInt(data);
        if (inBetweenGroupZero2 != 0) {
            data.position(resetPosition);
            return Optional.empty();
        }
        return Optional.of(group);
    }

    //specOps with leading 01
    private static Optional<List<CombatGroupMember>> getCombatGroupFromCodeV1_01SpecOps(ByteBuffer data) {
        int resetPosition = data.position();
        int groupNumber = readInt(data); //the number of the group, can be different from the group count (most likely groups in the middle where removed)
        int version = readInt(data);
        if (version != 1) {
            data.position(resetPosition);
            return Optional.empty();
        }
        int reinforcement = readInt(data);
        int combatGroupSize = readInt(data);
        int subVersion = readInt(data);

        List<CombatGroupMember> group = new ArrayList<>();
        for (int i = 0; i < combatGroupSize; i++) {

            CombatGroupMember groupMember;
            final int unitId = readInt(data);
            final int groupId = readInt(data);
            final int optionId = readInt(data);

            Integer zero = tryReadInteger(data);
            if (zero == null || zero != 0) {
                data.position(resetPosition);
                return Optional.empty();
            }

            Integer specOpsDataFlag = tryReadInteger(data);
            if (specOpsDataFlag == null || !Set.of(0, 1).contains(specOpsDataFlag)) {
                data.position(resetPosition);
                return Optional.empty();
            }

            Optional<List<String>> optionalModifier = specOpsDataFlag == 1 ? readMod(data) : Optional.empty();

            groupMember = new CombatGroupMember(
                    unitId,
                    groupId,
                    optionId,
                    optionalModifier.orElse(List.of())
            );
            group.add(groupMember);
            //not behind the last in the group
            if (i < combatGroupSize - 1) {
                int memberFillerZero1 = readInt(data);
                if (memberFillerZero1 != 0) {
                    data.position(resetPosition);
                    return Optional.empty();
                }
            }
        }
        if (group.size() != combatGroupSize) {
            data.position(resetPosition);
            return Optional.empty();
        }
        if (group.stream().anyMatch(m -> m.unitId() == 0)) {
            data.position(resetPosition);
            return Optional.empty();
        }
        return Optional.of(group);
    }

    private static void debug(ByteBuffer data) {
        data.mark();
        StringBuilder out = new StringBuilder();
        while (data.hasRemaining()) {
            byte b = data.get();
            if (b >= 32 && b <= 126) {
                char c = (char) b;
                out.append(c);

            } else {
                int value = b & 0xFF;
                out.append(value);
            }
        }
        data.reset();
        System.out.println(out);
    }

    private static void readNumbersTillEnd(ByteBuffer data) {
        int resetPosition = data.position();
        StringBuilder out = new StringBuilder();
        while (data.hasRemaining()) {
            out.append(readInt(data));
            out.append("-");
        }
        data.position(resetPosition);
        System.out.println(out);
    }

    private static byte[] decodeArmyCode(String armyCode) {
        // Sometimes CB urlencodes the army code and sometimes it doesn't.
        try {
            return Base64.getDecoder().decode(armyCode);
        } catch (IllegalArgumentException exception) {
            try {
                String decoded = URLDecoder.decode(armyCode, StandardCharsets.UTF_8);
                return Base64.getDecoder().decode(decoded);
            } catch (Throwable t) {
                log.debug("Failed to decode army code: {} -> {}", armyCode, t.getMessage());
            }
        }
        return null;
    }

    private static String readString(ByteBuffer data, int length) {
        byte[] stringBytes = new byte[length];
        data.get(stringBytes, 0, length);

        return new String(stringBytes, StandardCharsets.UTF_8);
    }

    private static Optional<List<String>> readMod(ByteBuffer data) {
        List<String> modifier = new ArrayList<>();
        try {
            int numberOfModi = readInt(data);
            for (int i = 0; i < numberOfModi; i++) {
                int modiLength = readInt(data);
                String m = readString(data, modiLength);
                if (!m.contains("type")) {
                    return Optional.empty();
                }
                modifier.add(m);
            }
        } catch (Exception ex) {
            return Optional.empty();
        }
        return Optional.of(modifier);
    }

    public record CombatGroupMember(
            int unitId,
            int groupId,
            int optionId,
            List<String> modifier) {
        @Override
        @NonNull
        public String toString() {
            if (modifier == null || modifier.isEmpty()) {
                return "%d-%d-%d".formatted(unitId, groupId, optionId);
            }
            return "%d-%d-%d-%s".formatted(unitId, groupId, optionId, modifier);
        }
    }

    public record ArmyCodeData(
            int sectorialId,
            String sectorialName,
            String armyName,
            int maxPoints,
            Map<Integer, List<CombatGroupMember>> combatGroups) {
    }
}
