package de.twonirwana.infinity.armylist;

import com.google.common.annotations.VisibleForTesting;
import de.twonirwana.infinity.ArmyList;
import de.twonirwana.infinity.Sectorial;
import de.twonirwana.infinity.db.DataLoader;
import de.twonirwana.infinity.unit.api.UnitOption;
import lombok.NonNull;
import lombok.extern.slf4j.Slf4j;

import java.net.URLDecoder;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

/**
 * # Army Codes
 * These are the shorthand codes generated by Army builder representing an army. They are base64 encoded strings.
 * <p>
 * ## Numbers
 * Integers are stored using a form of variable length encoding. If the value is under 128, then it is stored in a byte normally.
 * For larger numbers, two bytes are used and the first bit of the first byte is set high to flag this.
 * Should a larger number still be required, then presumably it would go up to 6 bytes, but no number in the game gets remotely that high.
 * <p>
 * ## Strings
 * Strings are encoded in the form `length, text`. and are not null terminated. 0 is a valid value for string length (in which case the text part will be absent).
 * <p>
 * ## Code Structure.
 * The code can be broken down into two parts - the header and the combat groups.
 * <p>
 * ### Header
 * The header is laid out as follows:
 * ````
 * ID of sectorial (int)
 * Name of sectorial (string)
 * Name of the army (string) - defaults to ' '
 * Point _limit_ used (int)
 * Number of combat groups (int)
 * ````
 * <p>
 * ### Combat Groups
 * Each combat group is as follows:
 * ````
 * 10
 * combat group number (int)
 * number of members of the group (int)
 * combat group member (see below) x number of members
 * ````
 * <p>
 * #### Combat Group Members
 * Each of these corresponds to a line in the army list in army builder.
 * ```
 * 00 (an empty byte)
 * Unit ID (int)
 * Group choice (int)
 * Option choice (int)
 * 00 (an empty byte)
 * ```
 */

@Slf4j
public class ArmyCodeLoader {

    private static int readInt(ByteBuffer data) {
        byte firstByte = data.get();

        // If the highest bit is 0, it's a standard positive byte (under 128)
        if (firstByte >= 0) {
            return firstByte;
        }

        // Otherwise, the first bit was 1.
        // We clear that flag bit (firstByte & 0x7F), shift it up 8 spots,
        // and combine it with the next byte.
        byte secondByte = data.get();
        return ((firstByte & 0x7F) << 8) | (secondByte & 0xFF);
    }

    public static ArmyList fromArmyCode(final String armyCode, DataLoader dataLoader) throws IllegalArgumentException {
        ArmyCodeData armyCodeData;
        try {
            armyCodeData = mapArmyCode(armyCode);
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }
        Sectorial sectorial = dataLoader.getSectorialIdMap().get(armyCodeData.sectorialId);
        List<UnitOption> unitOptionList = dataLoader.getAllUnitsForSectorial(sectorial);

        Sectorial sectorialApiId = dataLoader.getAllSectorialIds().stream()
                .filter(s -> s.getId() == armyCodeData.sectorialId)
                .findFirst().orElseThrow(() -> new IllegalArgumentException("Could not find sectorial with id %d for %s".formatted(armyCodeData.sectorialId, armyCode)));
        Map<Integer, List<UnitOption>> combatGroups = armyCodeData.combatGroups.entrySet().stream()
                .collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().stream()
                        .flatMap(m -> findUnitOptions(m, unitOptionList).stream())
                        .toList()));
        return new ArmyList(sectorialApiId, armyCodeData.sectorialName, armyCodeData.armyName, armyCodeData.maxPoints, combatGroups);
    }

    @VisibleForTesting
    public static ArmyCodeData mapArmyCode(final String armyCode) {
        byte[] decoded = decodeArmyCode(armyCode);
        if (decoded == null) {
            throw new IllegalArgumentException("armyCode cannot be null");
        }

        ByteBuffer data = ByteBuffer.wrap(decoded);

        int sectorialId = readInt(data);
        int factionStringLength = readInt(data);

        String fractionName = readString(data, factionStringLength);

        // Get the army name, if set. The default army name is ' '.
        int armyNameLength = readInt(data);
        String armyName = null;
        if (armyNameLength > 0) {
            armyName = readString(data, armyNameLength);
        }

        int maxPoints = readInt(data);

        int combatGroupCount = readInt(data);
        Map<Integer, List<CombatGroupMember>> combatGroups = new HashMap<>();

        for (int i = 1; i <= combatGroupCount; i++) {
            combatGroups.put(i, getCombatGroupFromCode(data, i));
        }

        return new ArmyCodeData(sectorialId, fractionName, armyName, maxPoints, combatGroups);
    }

    public static List<String> missingUnitsInArmyCode(final String armyCode, DataLoader dataLoader) throws IllegalArgumentException {
        ArmyCodeData armyCodeData;
        try {
            armyCodeData = mapArmyCode(armyCode);
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }

        Sectorial sectorial = dataLoader.getSectorialIdMap().get(armyCodeData.sectorialId);
        List<UnitOption> unitsForSectorial = dataLoader.getAllUnitsForSectorial(sectorial);
        List<UnitOption> allUnits = dataLoader.getAllUnits();


        //todo validate modi
        return armyCodeData.combatGroups.values().stream()
                .flatMap(Collection::stream)
                .filter(m -> findUnitOptions(m, unitsForSectorial).size() != 1)
                .map(c -> {
                    Optional<String> unitName = allUnits.stream()
                            .filter(u -> u.getUnitId() == c.unitId())
                            .map(UnitOption::getUnitName)
                            .findFirst();
                    return unitName
                            .map(s -> "SectorialId: %d, UnitId: %d, GroupId: %d, OptionId: %d -> Unknown version of %s".formatted(armyCodeData.sectorialId, c.unitId(), c.groupId(), c.optionId(), s))
                            .orElseGet(() -> "SectorialId: %d, UnitId: %d, GroupId: %d, OptionId: %d".formatted(armyCodeData.sectorialId, c.unitId(), c.groupId(), c.optionId()));
                })
                .toList();
    }

    private static List<UnitOption> findUnitOptions(CombatGroupMember combatGroupMember, List<UnitOption> unitOptionList) {
        return unitOptionList.stream()
                .filter(uo -> uo.getUnitId() == combatGroupMember.unitId()
                        && uo.getGroupId() == combatGroupMember.groupId()
                        && uo.getOptionId() == combatGroupMember.optionId)
                .toList();
    }


    private static boolean matchAndSkip(ByteBuffer data, int[] pattern) {
        boolean matches = nextIs(data, pattern);
        if (matches) {
            for (int i = 0; i < pattern.length; i++) {
                readInt(data);
            }
        }
        return matches;
    }

    private static List<CombatGroupMember> getCombatGroupFromCode(ByteBuffer data, int combatGroupId) {
        int groupCounter = readInt(data);
        if (combatGroupId != groupCounter) {
            log.error("Combat group id mismatch, shout be: {} but was {} ", groupCounter, combatGroupId); //todo some cases in tests, should check
        }
        int version = readInt(data);
        if (version > 1) {
            log.error("new version: " + version);
        }
        Integer reinforcement = null; //reinforcement ?0 no, 1 yes
        if (version == 1) {
            reinforcement = readInt(data);
        }
        int combatGroupSize = readInt(data);
        /*
        normally 0, but in one known case it is 1 or 3
         - value=3: there is an additional counter, the second unit has a 4, the third a 5 ...
         */
        Integer subVersion = null;
        if (version == 1) {
            subVersion = readInt(data);
            if (subVersion != 0 && subVersion != 3) {
                log.error("new subVersion: " + subVersion); //todo check value: 1
                // System.out.println("New Combat group: " + combatGroupId + " size: " + combatGroupSize + " version: " + version + " subVersion: " + subVersion + " reinforcement: " + reinforcement);
            }
        }
        //System.out.println("New Combat group: " + combatGroupId + " size: " + combatGroupSize + " version: " + version + " subVersion: " + subVersion + " reinforcement: " + reinforcement);
        final AtomicInteger additionalUnitCounter;
        if (subVersion == null) {
            additionalUnitCounter = null;
        } else {
            additionalUnitCounter = new AtomicInteger(subVersion);
        }
        List<CombatGroupMember> result = new ArrayList<>();
        if (version == 0) {
            matchAndSkip(data, new int[]{0});
        }
        for (int i = 0; i < combatGroupSize; i++) {
            if (version == 0) {
                matchAndSkip(data, new int[]{(i + 1)});
            }
            result.add(getCombatGroupMemberFromCode(data, version, additionalUnitCounter));
            if (version >= 1 && (i < combatGroupSize - 1)) { //for version 1 in between all units but not behind the last
                int inBetweenMemberZero = readInt(data); //always 0
            }
        }
        if (nextIs(data, new int[]{0, (groupCounter + 1)})) { //sometimes there is a 0 in between the group and the next, but not always
            readInt(data);
        }

        return result;
    }

    private static CombatGroupMember getCombatGroupMemberFromCode(ByteBuffer data, int version, AtomicInteger additionalUnitCounter) {
        if (additionalUnitCounter != null && additionalUnitCounter.get() > 2) {
            matchAndSkip(data, new int[]{additionalUnitCounter.getAndIncrement()});
        }

        CombatGroupMember result;
        final int unitId = readInt(data);
        final int groupId = readInt(data);
        final int optionId = readInt(data);
        // System.out.println("UnitId: " + unitId + "-" + groupId + "-" + optionId);

        boolean possibleModi;
        int resetPosition = data.position();
        if (version > 0) {
            possibleModi = matchAndSkip(data, new int[]{0, 1});
        } else {
            possibleModi = false;
        }
        List<String> modifier = new ArrayList<>();

        if (possibleModi) {
            try {
                int numberOfModi = readInt(data);
                for (int i = 0; i < numberOfModi; i++) {
                    int modiLength = readInt(data);
                    String m = readString(data, modiLength);
                    if (!m.contains("type")) {
                        throw new IllegalArgumentException("Invalid Mod"); //todo version without exception
                    }
                    modifier.add(m);
                }
            } catch (Exception ex) {
                data.position(resetPosition);
                log.error(ex.getMessage());
                possibleModi = false;
            }
        }

        if (!possibleModi) {
            if (version == 1 && nextIs(data, new int[]{0, 0, 0}) ||
                    (version == 0 && nextIs(data, new int[]{0, 0}))) {
                readInt(data);
                readInt(data);
            } else {
                matchAndSkip(data, new int[]{0});
            }
        }
        result = new CombatGroupMember(
                unitId,
                groupId,
                optionId,
                modifier
        );
        return result;
    }


    private static void debug(ByteBuffer data) {
        data.mark();
        StringBuilder out = new StringBuilder();
        while (data.hasRemaining()) {
            byte b = data.get();
            if (b >= 32 && b <= 126) {
                char c = (char) b;
                out.append(c);

            } else {
                int value = b & 0xFF;
                out.append(value);
            }
        }
        data.reset();
        System.out.println(out);
    }

    private static void readNumbersTillEnd(ByteBuffer data) {
        data.mark();
        StringBuilder out = new StringBuilder();
        while (data.hasRemaining()) {
            out.append(readInt(data));
            out.append("-");
        }
        data.reset();
        System.out.println(out);
    }

    private static byte[] decodeArmyCode(String armyCode) {
        // Sometimes CB urlencodes the army code and sometimes it doesn't.
        try {
            return Base64.getDecoder().decode(armyCode);
        } catch (IllegalArgumentException exception) {
            try {
                String decoded = URLDecoder.decode(armyCode, StandardCharsets.UTF_8);
                return Base64.getDecoder().decode(decoded);
            } catch (Throwable t) {
                log.debug("Failed to decode army code: {} -> {}", armyCode, t.getMessage());
            }
        }
        return null;
    }

    private static String readString(ByteBuffer data, int length) {
        byte[] stringBytes = new byte[length];
        data.get(stringBytes, 0, length);

        return new String(stringBytes, StandardCharsets.UTF_8);
    }


    private static boolean nextIs(ByteBuffer data, int[] expected) {
        if (!data.hasRemaining()) {
            return false;
        }
        int resetPosition = data.position();
        for (int c : expected) {
            if (!data.hasRemaining()) {
                data.position(resetPosition);
                return false;
            }
            int next = readInt(data);
            if (next != c) {
                data.position(resetPosition);
                return false;
            }
        }
        data.position(resetPosition);
        return true;
    }

    public record CombatGroupMember(
            int unitId,
            int groupId,
            int optionId,
            List<String> modifier) {
        @Override
        @NonNull
        public String toString() {
            if (modifier == null || modifier.isEmpty()) {
                return "%d-%d-%d".formatted(unitId, groupId, optionId);
            }
            return "%d-%d-%d-%s".formatted(unitId, groupId, optionId, modifier);
        }
    }

    public record ArmyCodeData(
            int sectorialId,
            String sectorialName,
            String armyName,
            int maxPoints,
            Map<Integer, List<CombatGroupMember>> combatGroups) {
    }
}
